apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sl2y2xk0j-python
  janus-idp.io/tekton: sl2y2xk0j-python
  backstage.io/kubernetes-id: sl2y2xk0j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sl2y2xk0j-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
