apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sl2y2xk0j-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sl2y2xk0j-python 
  name: sl2y2xk0j-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sl2y2xk0j-python
    weight: 100 
