apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sl2y2xk0j-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sl2y2xk0j-python 
  name: sl2y2xk0j-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sl2y2xk0j-python 
